apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: open-vm-tools
    app.kubernetes.io/name: open-vm-tools
  name: open-vm-tools
  namespace: open-vm-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-vm-tools
      app.kubernetes.io/name: open-vm-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: open-vm-tools
        app.kubernetes.io/name: open-vm-tools
    spec:
      affinity:
        nodeAffinity: null
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: open-vm-tools
                    app.kubernetes.io/name: open-vm-tools
                namespaces:
                  - open-vm-tools
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - image: 'docker.io/arnegroskurth/open-vm-tools:sha-fa19579'
          imagePullPolicy: IfNotPresent
          name: open-vm-tools
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/etc/cni/net.d
              name: cni
            - mountPath: /host/opt/cni/bin
              name: cnibin
            - mountPath: /tmp/multus-conf
              name: multus-cfg
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeName: rachel-lin-k8w.jkt2.mci.net.id
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
      serviceAccountName: default
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /etc/cni/net.d
          name: cni
        - hostPath:
            path: /opt/cni/bin
          name: cnibin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
