{{- if and .Values.networkPolicy.enabled .Values.metrics.enabled }}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "unifi.metrics.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  ingress:
    - ports:
        - port: {{ .Values.metrics.service.ports.metrics }}
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: prometheus
    {{- if .Values.metrics.webserver.enabled }}
    - ports:
        - port: {{ .Values.metrics.service.ports.http }}
          protocol: TCP
    {{- end }}
  policyTypes:
    - Ingress
{{- end }}